### ISSUE TITLE
uses too much ram

### ISSUE THREAD

**Issue by metemeto** [WilloIzCitron/ArchiveDustry-Java#11]
when the game is opened more than 5 mins it starts to use more than 4 gigs of ram

**Comment by metemeto** [comment]
which makes it unplayable

**Comment by WilloIzCitron** [comment]
![image](https://github.com/user-attachments/assets/53bb6f41-605c-4288-8fe9-b9fb320c0c9b)
I tried on my machine (12gb), I only in menu screen. it tooks 98mb. if you on the map, it rose 1-2GB RAM Usages depends how much unit you made (1 halo loads/unit, it counts effects). if you got over it, maybe you played on servers. GargabeCollection tried to clean the ram usage because the cache.

**Comment by metemeto** [comment]
when playing campaign or anything it rises to 5.5 gig then crashes no matter whatever i do, plus i play on android if that helps

**Comment by metemeto** [comment]
so, do you think this is fixable or it will remain like this

**Comment by WilloIzCitron** [comment]
I'll do best i can, it couldn't be resolved, i only prevents to skyrocketing

**Comment by metemeto** [comment]
remind me if you do it please

**Comment by WilloIzCitron** [comment]
fixed in 5dd6f73de013fccdc7b38304e20b38b7bae32267
