### ISSUE TITLE
No halos for flying units

### ISSUE THREAD

**Issue by CanOfDew132** [WilloIzCitron/ArchiveDustry-Java#8]
There are no halos for flying units (and boosting units when they fly) because there are halos, they're just under the unit

pls fix

**Comment by WilloIzCitron** [comment]
Yeah, because the layer of effect and/or bullets intended for bloom are lower than the layer what the flying unit use. You know, Meep just publish the pull request for secondary bloom layer for flying units. Unfortunately, the pull was unmerged from now. I think it could be a intentional problem I have on my memory....

**Comment by CanOfDew132** [comment]
also, the unit item inventory thing is under the halo (i added images)

boosting
<img width="960" alt="Screenshot 2024-07-18 145710" src="https://github.com/user-attachments/assets/49c0eb91-9c23-42f8-b11b-0bd1b43e167f">

not boosting
<img width="960" alt="Screenshot 2024-07-18 145631" src="https://github.com/user-attachments/assets/0d99ea53-7315-4047-b4db-bddd332cefda">

**Comment by WilloIzCitron** [comment]
Yes, Nova, Pulsar and Quasar boost is on flying layer. but vela boost on low-flying layer. The effect of halo will be overlapped with flying layer. i will make it wontfix if i even't research how do i make the custom layer renderer (if applied, it will conflicted with built-in Layer Renderer)

**Comment by CanOfDew132** [comment]
oh
